### PR TITLE
Support for Clipping Representation 

### PR DESCRIPTION
**Pull request by apemann**
This is a work in progress. The code is not clean (e.g. mapClipping function will be broken up).

The tricky part is positioning and orientating the clipping geometries i.e. converting the IfcAxis2Placement3D properties to ThreeJS  properties. Let me know if you have any ideas about this.

### CODE REVIEW

**Comment by agviegas** [comment]
I have made some additions to your code. Also, I have implemented the first draft of the logic for [IfcPolygonalBoundedHalfSpace ](https://iaiweb.lbl.gov/Resources/IFC_Releases/R2x3_final/ifcgeometricmodelresource/lexical/ifcpolygonalboundedhalfspace.htm)instances, which are a subclass that may occur to define the clipping volume. I am getting the following results:

image
image

There is still work to be done, because the floor is not beeing clipped correctly. This is the result of the current logic:
image

And this is what I see in BIMvision:
image
Nonetheless, I think that we are on the right track! 🚀

**Comment by agviegas** [comment]
Indeed, that floor slab has two `IfcHalfSpaceSolid` instances, but for some reason, it is creating them parallel to the slab. We must be missing a parameter / a condition of the IFC schema that let us know the orientation of the elements (?) Or maybe I have to debug the position algorithm to see if there is anything wrong with it applied to this case. Either way, I think that we are close. 
Here you see both planes represented as parallelepipeds (without applying CSG and making them short in height):
image

**Comment by apemann** [comment]
Great work! Yes the relationship between the axis, RefDirection and agreement flag wasn't entirely clear to me either given that "RefDirection does not have to be orthogonal to Axis". I would have expected this to be necessary based on how I understood it, which means I clearly haven't understood it! xD

This is one way to learn about IFC!

**Comment by agviegas** [comment]
I think that the issue lies on the fact that I have not implemented the direction for the extrusion. [This ](https://stackoverflow.com/questions/25639268/three-js-extrudegeometry-using-depth-and-a-direction-vector) looks promising. This means that the clipping planes of the floor slab are for nothing, but the *Direction* property of the extrusion body of the slab looks like what we need to get the correct shape.

Don't worry! IFC is really confusing and the documentation is really bad. In fact, I started this project to learn more about IFC. 😁

**Comment by apemann** [comment]
The documentation contradicts itself here:
"The location and orientation in three dimensional space of three **mutually perpendicular** axes. An axis2_placement_3D is defined in terms of a point (inherited from placement supertype) and two (**ideally orthogonal**) axes"

How can you say the axes are mutually perpendicular but then that they're only "ideally orthogonal"?

The description of RefDirection gives some clue:
"If necessary an adjustment is made to maintain orthogonality to the Axis direction"

This is frustratingly ambiguous! Does this mean that you need to find the closest orthogonal direction the Axis (z-direction) based on the RefDirection? Why would they do that instead of just recording the actual direction of the x-axis?

**Comment by apemann** [comment]
> I think that the issue lies on the fact that I have not implemented the direction for the extrusion. [This ](https://stackoverflow.com/questions/25639268/three-js-extrudegeometry-using-depth-and-a-direction-vector) looks promising. This means that the clipping planes of the floor slab are for nothing, but the _Direction_ property of the extrusion body of the slab looks like what we need to get the correct shape.

That looks like it would work. However there must be a reason for the clipping planes being there?

**Comment by agviegas** [comment]
> The documentation contradicts itself here:
> "The location and orientation in three dimensional space of three **mutually perpendicular** axes. An axis2_placement_3D is defined in terms of a point (inherited from placement supertype) and two (**ideally orthogonal**) axes"
> 
> How can you say the axes are mutually perpendicular but then that they're only "ideally orthogonal"?
> 
> The description of RefDirection gives some clue:
> "If necessary an adjustment is made to maintain orthogonality to the Axis direction"
> 
> This is frustratingly ambiguous! Does this mean that you need to find the closest orthogonal direction the Axis (z-direction) based on the RefDirection? Why would they do that instead of just recording the actual direction of the x-axis?

Yes,  I totally agree. The documentation is very verbose, confusing and sometimes contradictory. To be honest, I understand IFC better when I am debugging than when I am reading the documentation. 😅

**Comment by agviegas** [comment]
I have archieved this making a first implementation of the extrude direction using the shear matrix as suggested in the link above. I need to improve it and clean up, but the result is what we wanted: 

image

I can't figure out what the other clipping planes are for . That aside, I could not resist to load a bigger project that we are now able to support thanks to this PR. This is a great step forward. I will clean this up and push the changes throughout these days. 🚀

image
image
image

**Pull request merged**
