### PR TITLE
Typescript #24

### PR DESCRIPTION
**Pull request by vegarringdal**
DO NOT MERGE... I really dont know if Ive broken anything.. 😂  

Tested some migration tools I found, they did most of the JS to TS part.
Its added `:any` everywhere and did some of these 152 places where it did not know what to do: 
image

Updated the rollup bundler config, from what I can tell it works good.

Also added simple dev helpers Ive wrapped around [esbuild](https://esbuild.github.io/) (reeeeeeally fast bundler)

`npm start` to start dev mode

image

if you remove or just add a few more // then you also see the error in dev mode when saving

image

### CODE REVIEW

**Comment by vegarringdal** [comment]
hi

Like we talked on discord, understand if you want to focus on features/stability first of all.
I used this for migration, so doing it again should not be a big problem:
https://github.com/airbnb/ts-migrate/tree/master/packages/ts-migrate

**Comment by agviegas** [comment]
TypeScript would really make the library more robust and mantainable. As we talked, we will leave this open for later (when all the basic functionalities are working). Great work! 👌

**Comment by sinsunsan** [comment]
@vegarringdal  can you add WIP:  in the PR title to clarify it is not to be merged? 
Also I think GitHub prevent merging by error this type of PR (at least gitlab do it).

**Comment by vegarringdal** [comment]
I think its better if we just close this for now.
Something to think about later :-)

**Comment by vegarringdal** [comment]
For later:
Also before trying to implement typescript it would be useful to take out the global into a own module and get instance using function. And some of the auto executing functions when some modules are loaded might be useful to move into init functions.

**Pull request closed without merging**
