### PR TITLE
Refactoring: core is not related to UI and threejs Scene. It returns ready object. 

### PR DESCRIPTION
**Pull request by mudin**
Hello @agviegas, 

If you like this PR and merge it. There are some issues in core that I couldn't fix. 
I separate the UI and core part and threejs scene. 
Core part parse ifc file text string, converts to threejs objects and returns the root object.
It will be easy to use as threejs plugin and IFCLoader for threejs later.

core part is in src folder
examples go to demo folder (we can rename it), made by vue3 and element+

I believe this is better way to go.

Best regards,
Mudin

### CODE REVIEW

**Comment by mudin** [comment]
@agviegas Please check the latest one. I fixed other issues and added uploader for you :)

**Comment by agviegas** [comment]
Hey @mudin, congratulations on the PR! 

I have some questions about it:

1. What is the difference between the three vercel links?
2. It seems that in the last version of deploy only the edges are being represented; almost all the meshes are gone (see image below). 
3. I think the `build` folder is great. Sorry for the question, but I've only been using JavaScript for a short time: how did you make it? What's the difference between the three files it contains? I understand that these files are analogous to those to the build folder of three.js, right?
4. I think the separation between the core and the UI is very good. Nevertheless, I have my doubts about the demo being in Vue / element+; fundamentally, because I assume that this library can be mantained by and used by people from many backgrounds, and I think that coupling Vue / element + to the example can be limiting for people who don't know them (among which I include myself). Therefore, and although I'm aware that the final result might not be so attractive, I propose that the example is a simple application in HTML and CSS, framework agnostic. We can study the possibility of making several examples in several frameworks, although I don't know if it would be worth doing it in separate repositories. In any case, I consider that the main demo should be accesible to anyone.
5. For the same reason as the above, I think it would be great if the deploy could be done in an agnostic environment like github pages, at least for now.
6. What is the `rollup` folder for?
7. What is the `prettierrc` file for?

I think this is a phenomenal job; if we make it a little more agnostic it can be easier to maintain by future collaborators and to use by future users. What do you think?

Captura

**Comment by mudin** [comment]
Thank you for your response.

1. Vercel links are the same now. They are used for differentiating production, current and staging 

2. Yes right, I need your help for this part 

3. Build folder is for the release, when we publish to npm, it will be imported by other developers according to their development environment. It supports commonjs, module and just JavaScript. **npm run watch/build** will create/update the files in it

4. I think demo is just an example of how to use the library. People don't need to know vuejs. Usually core part will be developed and UI part will stay as it is. And demo is just for showing the result.
It doesn't matter what frameworks we use for demo. It will be ignored in npm package too. We can add normal html/js example too. There will be problem with importing libraries. Vue and Element UI make the demo easy to maintain. 


5. Okay, no problem at all. Good thing about vercel, it deploys as you push to git. You don't need to extra work.

6. Rollup folder includes configs related to rollup. Most libraries use rollup or webpack. Threejs uses rollup to build and minify the library

7. This file for prettier. If you set up your vscode, it format and lint on save. This helps to keep code clean

Sorry my explanation skill is not good :(

**Comment by agviegas** [comment]
Sounds good, thank you for the explanations! 🙂

I think for now it is better to stick to HTML and CSS, as Vue is not familiar to me and may make it difficult to solve some of the problems that will arise in these early stages of the project;  I can't compromise myself to mantain Vue code right now. Maybe we can add an additional Vue Demo once we have everything up and running in the Core. Github pages also updates with pushes; one difference is that the URL points to the github repository, which I think is better than pointing to the vercel URL. 

I have just noticed that the deploy in vercel is not supporting mobile devices either. Instead of merging the full PR and try to find the errors (which might take some time), I think it will be easier if:

1. I make some commits to the current repository to decouple the GUI and the core and emulate the architecture you are proposing, ensuring that everything works. 
2. You merge these changes in your PR, ensuring that everything works with rollup, prettier, etc (and without Vue).
3. I merge your PR in the repository. 

What do you think?

**Comment by mudin** [comment]
@agviegas I like it!
I will push my code without Vue!

**Comment by agviegas** [comment]
Great! I will also make my commits and change the architecture to fit your proposal throughout the following days.

**Comment by mudin** [comment]
Hi @agviegas!
I have pushed new examples without VueJS.
Building the library issues are fixed as well.
It is more organized now!

Hope you like it

Mudin

**Comment by agviegas** [comment]
One last question: I see that we are using both webpack and rollup. Can't we just stick to rollup for simplicity? Or is webpack necessary for the examples?

**Comment by mudin** [comment]
It is a good question. I tried to use only rollup and spent hours, but I couldn't make it :(
After we build the examples. we need to deploy `examples/dist`folder for online demo.

**Comment by agviegas** [comment]
I am changing the structure of the code to prepare the merge of this PR and ensure that everything still works. So far I have integrated basic Rollup functionality following the structure of folders you have proposed. I have managed to generate a working ES bundle of the project, so I think that we are close to archieve this. 🙂 Once I have the structure set up and the bundles working, I will merge this and include your example and other changes.

I have noticed that a lot of the problems in the bundling process were coming from including chevrotain in the bundle. I have taken a look into another `THREE` Loaders that use `chevrotain` (f. e. [VRMLoader](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/VRMLLoader.js)). Notice that `chevrotain` is not included in the bundle, but referenced as an external dependency. I think it is better to follow this pattern (not including `chevrotain` in the bundle). For this reason, `chevrotain` must be included in the HTML of the examples as a script. This should work once we adapt this to the [PR to `THREE`](https://github.com/mrdoob/three.js/pull/20598).

**Comment by mudin** [comment]
Congratulations!
I am glad you have managed it.
Let me do the work related to `chevrotain`.
I agree. It is better to exclude from the bundle.
Same as THREE, it will be external.

**Comment by agviegas** [comment]
A couple of important points about this merge:

- Thank you! The library has a much better structure right now. I think this has been an amazing contribution to the project. 🙂

- The library has been completely decoupled from the rest. The entry point is the file THREE.js. For now I have only made one method public (`loadIfc`), but we can make every step of the parsing public in case anyone wants to work with this information. 

- As you can see, there are two builds in the build folder: `THREE.js` (_iife_) and `THREE.module.js` (_ES modules_). I have not generated the minified version because chevrotain's logic seems to have some troubles with it. I have tried both uglify and terse, but maybe you can find a solution. Nevertheless, this is something that I don't consider important, as the Three.js loaders are not minified, so this is not a must.

- I am only using a few Rollup plugins, as they seem to be enough to archieve what we want. As a general rule, I'd rather install only the dependencies that we need.

- I have put your example in the folder examples/03. Feel free to develop it as you want. You can check how examples 01 and 02 work to make yours work as well with any of the builds. Notice that 01 is using IFC.js and 02 is using IFC.module.js; you can do whatever you prefer. This should be easy, but feel free to ask me anything you need regarding this.

- My idea is to delete examples 01 and 02 once the library is able to load any IFC and stick with 00.  This is the only example I will mantain. Yoy are free to add as many examples as you want in the library, as long as you make sure that they work properly with at least one of the builds. 

- If you want to develop a bigger example (more logic / menus / using frameworks, etc), I would rather have it in a separate repo in orther to keep this as clean as possible! This would be a great contribution as well.

Looking forward to seeing more of your PRs! 🙂

**Comment by mudin** [comment]
Hi @agviegas.
Sorry for the late response.
I think your mistake IFC.js/IFC.module.js and THREE.js/THREE.module.js.
I will try to minify it.
And I kept only one example and load multiple models.
Many examples for each model is not needed.

**Pull request merged**
